baseURL = "https://sk3.jsiu.dev"
theme   = "sk3"
title   = "SK3"

enableGitInfo = true
#paginate      = 24
DefaultContentLanguage = "en"
enableInlineShortcodes = true
languageCode           = "en"
paginate               = 3
relativeURLs           = true

#disqusShortname = ""
#googleAnalytics = ""

disqusShortname = "https-johnsiu-com"
googleAnalytics = "UA-36805525-1"     # optional

[Params]
#maintype  = "post"
pagewidth = "1024px"
startdate = "2012-12-02"
subtitle  = "A Hugo Themes"
toc       = true

homepage = false
# AdSense
adsense = ""

opengraph   = false
twitercards = false
# Fill in following if using opengraph / twitter card
description = "A Hugo Theme"
images      = [ "site-feature-image.jpg" ]
title       = "SK3"

	[Params.sociallink]
	facebook       = "john.siu.714"
	flickr         = "johnsiu-com"
	instagram      = "john.sd.siu"
	linkedin       = "john-sing-dao-siu"
	pinterest      = "johnsdsiu"
	reddit         = "js1943"
	tumblr         = "jsds"
	twitter        = "JohnSiuCom"
	vimeo          = "user88929197"
	youtubechannel = "UC5LvdqfL2PubOp904UnUJAg"
	youtubeuser    = "JohnSDSiu"

	[Params.socialshare]
	facebook  = true
	instagram = true
	linkedin  = true
	pinterest = true
	reddit    = true
	telegram  = true
	twitter   = true
	vk        = true

	[Params.card]
	date    = true
	summary = true
	#width   = "100%"

	[Params.color]
	bg     = "#181a1b"
	border = "white"
	link   = "#3d84ff"
	text   = "white"

	# [menu]
	# 	[[menu.main]]
	# 	identifier = "about"
	# 	name       = "About"
	# 	url        = "/about/"
	# 	weight     = 10
	# 	[[menu.main]]
	# 	name = "Tags"
	# 	url  = "/tags/"

[markup]
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 3
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    #style = "monokai"
    tabWidth = 4