# Config file for demo site https://sk3.jsiu.dev
#
# This is used in combine with exampleSite/config.toml

baseURL = "https://sk3.jsiu.dev"
theme   = "sk3"
title   = "SK3"

DefaultContentLanguage = "en"
enableGitInfo          = true
enableInlineShortcodes = true
googleAnalytics        = "UA-36805525-2"
languageCode           = "en"
paginate               = 3
relativeURLs           = true

[Params]
# mainSections = "post"
# pagewidth    = "1200px"
# startdate    = "2012-12-02"
adsense_id  = "ca-pub-8176479711832264"
pageinfobox = true
subtitle    = "A Hugo Theme"

# Fill in following if using opengraph / twitter card
description = "Hugo Theme SK3 Demo Site"
opengraph   = true
title       = "Hugo Theme SK3 Demo Site"
twitercards = true

	[Params.card]
	date    = true
	summary = true
	# width   = "32%"

	# [Params.color]
	# bg     = "#181a1b"
	# border = "white"
	# link   = "#3d84ff"
	# text   = "white"

	[Params.sociallink]
	facebook       = "john.siu.714"
	flickr         = "johnsiu-com"
	github         = "J-Siu"
	instagram      = "john.sd.siu"
	linkedin       = "john-sing-dao-siu"
	pinterest      = "johnsdsiu"
	reddit         = "js1943"
	tumblr         = "jsds"
	twitter        = "JohnSiuCom"
	vimeo          = "user88929197"
	youtubechannel = "UC5LvdqfL2PubOp904UnUJAg"
	youtubeuser    = "JohnSDSiu"

	[Params.socialshare]
	facebook  = true
	instagram = true
	linkedin  = true
	pinterest = true
	reddit    = true
	telegram  = true
	twitter   = true
	vk        = true

[markup]
defaultMarkdownHandler = "goldmark"

	[markup.highlight]
	codeFences         = true
	guessSyntax        = false
	hl_Lines           = ""
	lineNoStart        = 1
	lineNos            = true
	lineNumbersInTable = true
	noClasses          = true
	style              = "fruity"
	tabWidth           = 4

	[markup.tableOfContents]
	endLevel   = 6
	ordered    = false
	startLevel = 1

	[markup.goldmark]
		[markup.goldmark.extensions]
		definitionList = true
		footnote       = true
		linkify        = true
		strikethrough  = true
		table          = true
		taskList       = true
		typographer    = true
		[markup.goldmark.parser]
		attribute         = true
		autoHeadingID     = true
		autoHeadingIDType = "github"
		[markup.goldmark.renderer]
		hardWraps = false
		unsafe    = true
		xhtml     = false
